#!/bin/python3

import sys
sys.path.append(".")

from adder_graph import adder_graph as graph
from adder_graph import adder_node as node
from adder_tree import adder_tree as tree

g = tree(8)
assert(g._checkLF(7,7)==(g[7,7],g[6,6]))
assert(g._checkLT(7,7)==(g[7,7],g[6,6]))
assert(g._checkLT(3)==(g[3,3],g[2,2]))
assert(g._checkLF(2,2)==(None,None))
assert(g._checkLT(2)==(None,None))

assert(g._checkFT(7)==(None,None,None))
assert(g._checkTF(7)==(None,None))
assert(g._checkFL(7)==(None,None))
assert(g._checkTL(7)==(None,None))

assert(len(g.node_list)==9)
g.trim_layer()
assert(len(g.node_list)==9)

def sklanksy():
    g.LF(7,clean=True)
    g.LF(5,clean=True)
    g.LF(3,clean=True)
    g.LF(7,clean=True)
    g.LF(6,clean=True)
    g.png('sklansky.png')

def koggestone():
    g.LT(7,clean=True)
    g.LT(5,clean=True)
    g.LT(3,clean=True)
    g.LT(7,clean=True)
    g.LT(6,clean=True)
    g.png('koggestone.png')

def brentkung():
    g.LF(7)
    g.compress()
    g.LF(5)
    g.compress()
    g.LF(3)
    g.trim_layer()
    g.trim_layer()
    g.compress()
    g.LF(7)
    g.shift_node(g[4,3],g.bot)
    g.shift_node(g[4,4],g.bot)
    g.png('1.png')
    g.shift_node(g[6,4],g.bot)
    g.png('2.png')
    g.shift_node(g[5,3],g.bot)
    g.shift_node(g[2,2],g.bot)
    g.shift_node(g[2,3],g.bot)
    g.shift_node(g[2,4],g.bot)
    g.png('brentkung.png')

def demo():
    g=tree(8)
    g.png('00.png')
    g.png('01.png')
    g.png('02.png')
    g.png('03.png')
    g.png('04.png')
    g.LF(7)
    g.compress()
    g.png('05.png')
    g.LF(5)
    g.compress()
    g.png('06.png')
    g.LF(3)
    g.compress()
    g.png('07.png')
    g.LF(7)
    g.png('08.png')
    g.trim_layer()
    g.trim_layer()
    g.png('09.png')
    g.shift_node(g[4,3],g.bot)
    g.shift_node(g[4,4],g.bot)
    g.shift_node(g[6,4],g.bot)
    g.shift_node(g[5,3],g.bot)
    g.shift_node(g[2,2],g.bot)
    g.shift_node(g[2,3],g.bot)
    g.shift_node(g[2,4],g.bot)
    g.png('10.png')
    g.png('11.png')
    g.png('12.png')
    g.png('13.png')
    g.png('14.png')
    g.LF(6)
    g.png('15.png')
    g.compress()
    g.png('16.png')
    g.png('17.png')
    g.png('18.png')
    g.png('19.png')
    g.png('20.png')
    g.FT(7)
    g.png('21.png')
    g.FT(6)
    g.png('22.png')
    g.FT(7,2)
    g.png('23.png')
    g.FT(5,2)
    g.png('24.png')
    g.FT(3,2)
    g.png('25.png')
    g.FT(7)
    g.png('26.png')
    g.FT(5)
    g.png('27.png')
    g.png('28.png')
    g.png('29.png')
    g.png('30.png')
    g.png('31.png')
    g.TF(7,3)
    g.png('32.png')
    g.TF(5,3)
    g.png('33.png')
    g.TF(7,2)
    g.remove_node(g[6,1])
    g.add_node(node(6,1,'buffer_node'))
    g.png('34.png')
    g.TF(5,2)
    g.remove_node(g[4,1])
    g.add_node(node(4,1,'buffer_node'))
    g.png('35.png')
    g.TF(3,2)
    g.remove_node(g[2,1])
    g.add_node(node(2,1,'buffer_node'))
    g.png('36.png')
    g.png('37.png')
    g.png('38.png')
    g.png('39.png')
    g.png('40.png')

def LFT():
    g=tree(4)
    g.png('L.png')
    g.LF(3)
    g.png('F.png')
    g.FT(3)
    g.png('T.png')

def test():
    g.LF(7)
    g.LF(6)
    g.LF(7)
    g.LF(6)
    g.LF(5,clean=False)
    g.png('1.png')
    g.clean()
    g.png('2.png')
    g.LF(7)
    g.png('3.png')

test()
